
name: myway
description: My Way — AI-native, TikTok-style feed (Flutter)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  dio: ^5.5.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  firebase_remote_config: ^5.1.1
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  camera: ^0.11.0
  image_picker: ^1.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.10
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
